export enum ModalKey {
    WITHDRAW = "WITHDRAW",
    AIM_REMOVE = "AIM_REMOVE",
    PERSONAL_CABINET = "PERSONAL_CABINET",
    QUICK_LINK_REMOVE = "QUICK_LINK_REMOVE",
    ADVERTISING_MARKING = "ADVERTISING_MARKING",
    ADD_CARD = "ADD_CARD",
    CARDS_SHEET = "CARDS_SHEET",
    ADD_CARD_NOTIFICATION = "ADD_CARD_NOTIFICATION",
    UNLINK_PAYMENT_CARD = "UNLINK_PAYMENT_CARD",
    PAYOUTS_CALENDAR = "PAYOUTS_CALENDAR",
    SBP_PAYMENT = "SBP_PAYMENT",
    EMAIL_CHECK = 'EMAIL_CHECK',
    QUICK_LINK_DETAILS = 'QUICK_LINK_DETAILS',

    ANALYTICS_HISTORY = "ANALYTICS_HISTORY",
    ANALYTICS_SALES = "ANALYTICS_SALES",
    PAY_WITH_CARD = "PAY_WITH_CARD",
}
