export enum MutationKey {
    /** auth */
    AUTH_BY_SMS = 'AUTH_BY_SMS',
    AUTH_BY_SMS_VERIFY = 'AUTH_BY_SMS_VERIFY',
    AUTH_BY_TINKOFF = 'AUTH_BY_TINKOFF',
    AUTH_BY_TELEGRAM = 'AUTH_BY_TELEGRAM',
    AUTH_BY_TELEGRAM_VERIFY = 'AUTH_BY_TELEGRAM_VERIFY',

    /**finance */
    ADD_CARD = 'ADD_CARD',
    WITHDRAW = 'WITHDRAW',
    PAY_FOR_QUICK_LINK = 'PAY_FOR_QUICK_LINK',
    PAYMENT_STATUS_CHECK = 'PAYMENT_STATUS_CHECK',
    PAYMENT_REQUEST = 'PAYMENT_REQUEST',
    UNLINK_PAYMENT_CARD = 'UNLINK_PAYMENT_CARD',

    /**quick link */
    CREATE_QUICK_LINK = 'CREATE_QUICK_LINK',
    CREATE_QUICK_LINK_VALIDATION = 'CREATE_QUICK_LINK_VALIDATION',
    EDIT_QUICK_LINK = 'EDIT_QUICK_LINK',
    DELETE_QUICK_LINK = 'DELETE_QUICK_LINK',

    /** user */
    CREATE_UNIQUE_NICKNAME= 'CREATE_UNIQUE_NICKNAME',
    ADD_AVATAR= 'ADD_AVATAR',
    DELETE_AVATAR= 'DELETE_AVATAR',

    /** passport */
    CREATE_PASSPORT = 'CREATE_PASSPORT',
    EDIT_PASSPORT = 'EDIT_PASSPORT',
    VALIDATION_PASSPORT = 'VALIDATION_PASSPORT',
    DELETE_PASSPORT = 'DELETE_PASSPORT',

    /** passport rim */
    CREATE_PASSPORT_RIM = 'CREATE_PASSPORT_RIM',
    VERIFY_PASSPORT_RIM = 'VERIFY_PASSPORT_RIM',

    /** referral */
    CREATE_REFERRAL_LINK = 'CREATE_REFERRAL_LINK',

    /** common */
    UPLOAD_FILE= 'UPLOAD_FILE',
    SEND_TO_BUYERS_EMAIL= 'SEND_TO_BUYERS_EMAIL',
    ADD_FEEDBACK= 'ADD_FEEDBACK',

    /** UPLOAD */
    UPLOAD_CHUNK = 'UPLOAD_CHUNK',
    UPLOAD_COMPLETE = 'UPLOAD_COMPLETE',
SEND_CONTENT_MALE = 'SEND_CONTENT_MALE'
}
