export enum QueryKey {
  /**quick link */
  GET_OWNER_QUICK_LINKS = "GET_OWNER_QUICK_LINKS",
  GET_QUICK_LINK = "GET_QUICK_LINK",

  /**user */
  GET_USER = "GET_USER",
  GET_USER_LIMIT = "GET_USER_LIMIT",

  /**passport */
  GET_PASSPORT = "GET_PASSPORT",

  /**telegram */
  GET_AUTH_TELEGRAM = "GET_AUTH_TELEGRAM",

  /**referral */
  GET_REFERRAL_LINK_BY_CODE = "GET_REFERRAL_LINK_BY_CODE",
  CREATE_REFERRAL_LINK = "CREATE_REFERRAL_LINK",

  /**analytics */
  GET_INCOME = "GET_INCOME",

  GET_SALES = "GET_SALES",
  GET_FINANCE = "GET_FINANCE",
  GET_PAYOUTS = "GET_PAYOUTS",
  GET_INCOMING = "GET_INCOMING",
  GET_INCOMING_SEARCH = "GET_INCOMING_SEARCH",

  /**blog */
  GET_BLOG = "GET_BLOG",
  GET_POST = "GET_POST",

  /**finance */
  GET_LIMITS_BY_CARDS = "GET_LIMITS_BY_CARDS",
  GET_CAN_WITHDRAW = "GET_CAN_WITHDRAW",

  /**auth */
  GET_AVAILABLE_BY_SMS = "GET_AVAILABLE_BY_SMS",

  /**upload */
  UPLOAD_INIT = "UPLOAD_INIT",
}
