export const API_ENDPOINTS = {
  AUTH: {
    AUTH_BY_SMS: "auth/sms",
    AUTH_BY_SMS_VERIFY: "auth/sms/verify",
    AUTH_BY_SMS_TINKOFF: "auth/tinkoff",
    AUTH_BY_SMS_TINKOFF_VERIFY: "auth/tinkoff/verify",
    AUTH_BY_TELEGRAM_VERIFY: "auth/telegram/check",
    AUTH_BY_TELEGRAM: "auth/telegram",
    AUTH_AVAILABLE_BY_SMS: "auth/sms/available",
  },

  FINANCE: {
    ADD_CARD: "card/add",
    WITHDRAW: "withdraw",
    PAY_FOR_QUICK_LINK: "pay",
    PAYMENT_STATUS_CHECK: "pay/check",
    PAYMENT_REQUEST: "withdraw",
    UNLINK_PAYMENT_CARD: "card/id",
    GET_LIMITS_BY_CARDS: "limits",
    GET_CAN_WITHDRAW: "withdraw",
    SEND_CONTENT_MALE: "SEND_CONTENT_MALE",
  },
  QUICK_LINK: {
    CREATE: "quicklink/create",
    VALIDATION: "quicklink/precreate",
    EDIT: "quicklink/:id",
    DELETE: "quicklink/:id",
    GET_LINKS_BY_OWNER: "quicklink/:id",
    GET_LINK: "quicklink/:id",
  },
  USER: {
    CREATE_NICKNAME: "user/nickname",
    DELETE_USER_AVATAR: "user/avatar",
    GET_USER: "user",
    GET_USER_LIMIT: "user/limits",
  },
  PASSPORT: {
    CREATE: "passport/create",
    DELETE: "passport/:id",
    EDIT: "passport/:id",
    GET: "passport",
    VALIDATE: "passport/:id/validate",
    RIM_VERIFY: "auth/rim/verify",
    CREATE_RIM: "auth/rim",
  },
  REFERRAL: {
    CREATE_REFERRAL_LINK: "auth/referral/create",
    GET_REFERRAL_LINK: "auth/referral",
  },
  COMMON: {
    UPLOAD_FILE: "upload",
    SEND_TO_BUYERS_EMAIL: "sendmail",
    ADD_FEEDBACK: "feedback",
  },
  ANALYTICS: {
    GET_INCOME: "dashboard/payment/purchase/finances/sum",
    GET_SALES: "dashboard/payment/purchase/finances/count",
    GET_FINANCE: "dashboard/payment/purchase/finances",
    GET_INCOMING: "dashboard/payment/purchase/finances/incoming",
    GET_INCOMING_SEARCH: "dashboard/payment/purchase/finances/incoming/id?",
  },
  BLOG: {
    GET_BLOG: "post/get/post",
    GET_POST: "post/get/post",
  },
  UPLOAD: {
    INIT: "upload/chunkinit",
    CHUNK_UPLOAD: "/upload/chunkupload",
    COMPLETE_UPLOAD: "/upload/uploadcomplete",
  },
};
